### ISSUE TITLE
player for tandy?

### ISSUE THREAD

**Issue by ricardoquesada** [MobyGamer/MONOTONE#7]
It seems that monotone (the tracker) supports playing songs on the tandy.
but the player that is in the `Player` directory doesn't.

any chance to add tandy-1000 support to the player?
or what should I do in order to add it myself?

thanks.

**Comment by MobyGamer** [comment]
Tandy support was added more as a proof-of-concept rather than a committed feature.  If you want to produce and play back Tandy/PCjr audio, I highly suggest you have someone compose the music in MOD2PSG2 or Deflemask, both of which can export the audio as a .VGM, which is a very simple format to write a player for.  (Which is actually what I did for introJR and shakeJR)
